<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '"{attribute}" must be a valid JSON' => '"{attribute}" должен содержать валидный JSON',
    'Down to maintenance.' => 'Закрыто на обслуживание',
    'Active' => 'Активно',
    'Administrator' => 'Администратор',
    'Article ID' => 'ID Статьи',
    'Author' => 'Автор',
    'Body' => 'Текст',
    'Caption' => 'Текст',
    'Carousel ID' => 'ID карусели',
    'Category' => 'Категория',
    'Comment' => 'Комментарий',
    'Config' => 'Настройки',
    'Created At' => 'Создано',
    'Created at' => 'Создано',
    'Deleted' => 'Удалено',
    'E-mail' => 'E-mail',
    'Firstname' => 'Имя',
    'Gender' => 'Пол',
    'ID' => 'ID',
    'Key' => 'Ключ',
    'Lastname' => 'Фамилия',
    'Locale' => 'Локаль',
    'Manager' => 'Менеджер',
    'Middlename' => 'Отчество',
    'Order' => 'Порядок',
    'Parent Category' => 'Родительская категория',
    'Path' => 'Путь',
    'Picture' => 'Аватар',
    'Published' => 'Опубликовано',
    'Published At' => 'Дата публикации',
    'Role' => 'Роль',
    'Slug' => 'ЧПУ',
    'Status' => 'Статус',
    'Title' => 'Название',
    'Updated At' => 'Обновлено',
    'Updater' => 'Обновивщий',
    'Url' => 'Url',
    'User' => 'Пользователь',
    'User ID' => 'ID пользователя',
    'Username' => 'Имя пользователя',
    'Value' => 'Значение',

    'Goods' => 'Товары',
    'Create Goods' => 'Новый товар',
    'Create' => 'Создать',
    'Update' => 'Редактировать',
    'Delete' => 'Удалить',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить эту позицию?',

    'Idcat' => 'ID Категории',
    'Name' => 'Наименование',
    'Height' => 'Высота',
    'Hard' => 'Жесткость (число от 1 до 4)',
    'Gload' => 'Нагрузка (в кг)',
    'Cost1' => 'Цена (для матрасов цена для 80x200)',
    'Cost2' => 'Цена 90x200',
    'Cost3' => 'Цена 120x200',
    'Cost4' => 'Цена 140x200',
    'Cost5' => 'Цена 160x200',
    'Cost6' => 'Цена 180x200',
    'Sostav' => 'Состав (только для топлеров)',
    'Material' => 'Материал (кроме топлеров и матрасов)',
    'Pic' => 'Основное изображение',
    'Note1' => 'Комментарий 1',
    'Note2' => 'Комментарий 2',
    'Pic2' => 'Дополнительное изображение',
    'Bl1' => 'Пункт 1 нижнего блока комментариев',
    'Bl2' => 'Пункт 2 нижнего блока комментариев',
    'Bl3' => 'Пункт 3 нижнего блока комментариев',
    'Bl4' => 'Пункт 4 нижнего блока комментариев',
    'Bl5' => 'Пункт 5 нижнего блока комментариев',
    'Bl6' => 'Пункт 6 нижнего блока комментариев',
    'Bl7' => 'Пункт 7 нижнего блока комментариев',
    'Bl8' => 'Пункт 8 нижнего блока комментариев',
    'Bl9' => 'Пункт 9 нижнего блока комментариев',
    'Bl1pic' => 'Изображение к 1 пункту нижнего блока комментариев',
    'Bl2pic' => 'Изображение к 2 пункту нижнего блока комментариев',
    'Bl3pic' => 'Изображение к 3 пункту нижнего блока комментариев',
    'Bl4pic' => 'Изображение к 4 пункту нижнего блока комментариев',
    'Bl5pic' => 'Изображение к 5 пункту нижнего блока комментариев',
    'Bl6pic' => 'Изображение к 6 пункту нижнего блока комментариев',
    'Bl7pic' => 'Изображение к 7 пункту нижнего блока комментариев',
    'Bl8pic' => 'Изображение к 8 пункту нижнего блока комментариев',
    'Bl9pic' => 'Изображение к 9 пункту нижнего блока комментариев',

];
